// types로 대체 예정
export * from './isElement.js';
export * from './isFunction.js';
export * from './isNil.js';
export * from './isNotNil.js';
export * from './isNotNull.js';
export * from './isNotNullish.js';
export * from './isNotUndefined.js';
export * from './isNullish.js';
export * from './isNumber.js';
export * from './isPlainObject.js';
export * from './isString.js';
